title: Sample Lume Blog
description: I am writing about my experiences as a naval navel-gazer.
author:
  name: Vic G,
  email: youremailaddress@example.com,
  url: https://vicgupta.github.io/lume-blog/
